[package]
name = "easytcp"
version = "0.1.3"
edition = "2021"

[dependencies]
openssl = { version = "0.10.42", optional = true }
aes = { version = "0.8.1", optional = true }
cbc = { version = "0.1.2", optional = true }


[features]
tcp_openssl = ["dep:openssl"]
tcp_aes_cbc = ["dep:aes", "dep:cbc"]