[package]
name = "easytcp"
version = "0.1.2"
edition = "2021"

[dependencies]
openssl = { version = "0.10.42", optional = true }

#openssl = { version = "0.10", features = ["vendored"] }
#aes = "0.8.1"


[features]
tcp_openssl = ["dep:openssl"]